[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/backend"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"